/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_scheduler

type AddTaskResp struct {
	SessionId string `json:"session_id"`
	Name      string `json:"name"`
	TaskId    string `json:"task_id"`
}
