/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_scheduler

type HeartBeatResp struct {
	SessionId string `json:"session_id"`
	ErrorMsg  string `json:"error_msg,omitempty"`
}
