/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_scheduler

type AddTaskReq struct {
	SessionId string `json:"session_id"`
	Name      string `json:"name"`
	Input     string `json:"input"`
	TaskType  string `json:"task_type"`
}
