/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_scheduler

type TaskContent struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	TaskType   string `json:"task_type"`
	Input      string `json:"input,omitempty"`
	Output     string `json:"output,omitempty"`
	CommitTime int64  `json:"commit_time,omitempty"`
	BeginTime  int64  `json:"begin_time,omitempty"`
	EndTime    int64  `json:"end_time,omitempty"`
	Status     string `json:"status,omitempty"`
	WorkerId   string `json:"worker_id,omitempty"`
}
