/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version:
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go_scheduler

type WorkerContent struct {
	Id       string `json:"id,omitempty"`
	Name     string `json:"name"`
	TaskType string `json:"task_type"`
	Info     string `json:"info,omitempty"`
	Status   string `json:"status,omitempty"`
}
