# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from scheduler_py3.configuration import Configuration


class FetchTaskReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'str',
        'task_type': 'str',
        'worker_id': 'str'
    }

    attribute_map = {
        'session_id': 'session_id',
        'task_type': 'task_type',
        'worker_id': 'worker_id'
    }

    def __init__(self, session_id=None, task_type=None, worker_id=None, _configuration=None):  # noqa: E501
        """FetchTaskReq - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._session_id = None
        self._task_type = None
        self._worker_id = None
        self.discriminator = None

        self.session_id = session_id
        self.task_type = task_type
        self.worker_id = worker_id

    @property
    def session_id(self):
        """Gets the session_id of this FetchTaskReq.  # noqa: E501


        :return: The session_id of this FetchTaskReq.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this FetchTaskReq.


        :param session_id: The session_id of this FetchTaskReq.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def task_type(self):
        """Gets the task_type of this FetchTaskReq.  # noqa: E501


        :return: The task_type of this FetchTaskReq.  # noqa: E501
        :rtype: str
        """
        return self._task_type

    @task_type.setter
    def task_type(self, task_type):
        """Sets the task_type of this FetchTaskReq.


        :param task_type: The task_type of this FetchTaskReq.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and task_type is None:
            raise ValueError("Invalid value for `task_type`, must not be `None`")  # noqa: E501

        self._task_type = task_type

    @property
    def worker_id(self):
        """Gets the worker_id of this FetchTaskReq.  # noqa: E501


        :return: The worker_id of this FetchTaskReq.  # noqa: E501
        :rtype: str
        """
        return self._worker_id

    @worker_id.setter
    def worker_id(self, worker_id):
        """Sets the worker_id of this FetchTaskReq.


        :param worker_id: The worker_id of this FetchTaskReq.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and worker_id is None:
            raise ValueError("Invalid value for `worker_id`, must not be `None`")  # noqa: E501

        self._worker_id = worker_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FetchTaskReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FetchTaskReq):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FetchTaskReq):
            return True

        return self.to_dict() != other.to_dict()
